
try {
    throw new Error('Что-то пошло не так!');
} catch (error) {
    console.log(error);
}
